project:
  type: website

website:
  title: "Calc with Dec 🧮 🤓"
  navbar:
    right:
      - about.qmd
      - icon: envelope-fill
        href: mailto:declann1990@gmail.com
  #    - icon: linkedin
  #      href: https://linkedin.com
      - icon: twitter
        href: https://twitter.com/calculang
      - icon: github
        href: https://github.com/declann
      - icon: journal-code
        href: https://observablehq.com/@declann
  page-footer:
    left: "Made with 💓 and [calculang](https://github.com/calculang/calculang) and [Quarto](https://quarto.org/) and lots of 🧉 by [Declan Naughton](https://calcwithdec.dev/about.html)."
    right: "ℹ️ [Website Source Code](https://github.com/declann/calcwithdec.dev)"
  twitter-card: true # creator=@calculang?

format:
  html:
    theme:
      light: journal
      dark: darkly
    css: styles.css
    include-after-body: plausible.html    


